Transfert of code from bitbucket
scilus/tractometry_flow pull request #1
Opened 2020-07-02 23:37 UTC by frheault

Simple transfer of code, update call to scripts in order to work with scilpy master.
Simplified a bit the channel structure for centroids by adding the parameters `--use_provided_centroids` making edge-case simpler to detect.

Some channel were removed since all input are trk and that references are no longer needed.
Working just like before, for robustness it should be tested independently

2020-10-25 18:14 UTC, mdesco commented
can we call this one tractometry_flow please

2020-10-25 18:45 UTC, arnaudbore commented
> can we call this one tractometry_flow please

done

2020-11-07 19:50 UTC, mdesco reviewed
Should the bin/jq file be put in the singularity image?
This creates issues for people on different plateformes, no?

2020-11-07 19:50 UTC, mdesco commented on USAGE
> +--root=/path/to/[root]     Root folder containg multiple subjects
Please update to --input

2020-11-07 20:04 UTC, mdesco approved these changes
With my above modifications, everything runs.
Here is my main.nf
https://www.dropbox.com/s/kkpfqwz0d128vzc/main.nf?dl=0

2020-11-07 20:04 UTC, mdesco commented on main.nf
> +    scil_bundle_volume_per_label.py\
we have to also convert $voxel_label_map  to int16 before using it by scil_compute_bundle_volume_per_label.py
scil_image_math.py convert $voxel_label_map $voxel_label_map --data_type int16 -f 

I remember doing all these changes in the bitbucket! grrr....

2020-11-10 14:28 UTC, arnaudbore reviewed
Here are some suggestions (using Max comments)

2020-11-10 14:28 UTC, arnaudbore commented on USAGE
> +nextflow run main.nf [OPTIONAL_ARGUMENTS] (--root)
```suggestion
nextflow run main.nf [OPTIONAL_ARGUMENTS] (--input)
```

2020-11-10 14:28 UTC, arnaudbore commented on main.nf
> +    scil_bundle_volume.py $bundle > ${sid}__${bname}__volume_raw.json
```suggestion
    scil_compute_bundle_volume.py $bundle > ${sid}__${bname}__volume_raw.json
```

2020-11-10 14:28 UTC, arnaudbore commented on main.nf
> +    scil_bundle_voxel_label_map.py  $bundle $centroid ${sid}__${bname}__voxel_label_map.nii.gz
```suggestion
    scil_compute_bundle_voxel_label_map.py  $bundle $centroid ${sid}__${bname}__voxel_label_map.nii.gz
```

2020-11-10 14:28 UTC, arnaudbore commented on main.nf
> +    scil_bundle_volume_per_label.py\
```suggestion
    scil_image_math.py convert $voxel_label_map $voxel_label_map --data_type int16 -f 
    scil_compute_bundle_volume_per_label.py\
```

2020-11-10 14:28 UTC, arnaudbore commented on main.nf
> +    scil_bundle_mean_std_per_point.py --sort_keys $density_weighting $bundle\
```suggestion
    scil_compute_bundle_mean_std_per_point.py --sort_keys $density_weighting $bundle\
```

2020-11-18 19:18 UTC, mdesco commented
@frheault any chance we can prioritize tractometry_flow? 4 projects waiting on this on my end. Thanks!

2020-11-18 19:55 UTC, frheault commented
@mdesco it is ready for review and testing, I would simply say that the random coloring is pretty bad in its choice of color, but this is outside of the scope of this PR

2020-11-19 20:05 UTC, arnaudbore commented
Please remove jq since it's already in the scilpy docker.

2020-11-20 01:50 UTC, mdesco requested changes
Mini demande avant de faire le merge. On peut rajouter un process de scil_convert_json_to_xlsx.py des json finaux dans Statistics? 

Nos users le demandent toujours.

Thanks

2020-11-20 17:05 UTC, frheault commented
@mdesco I will remove JQ, let's merge and I will immediately do a new PR.
(I have to verify the converting work correctly for all json)

That's way we can start using it.

2020-11-20 17:07 UTC, frheault commented
@arnaudbore But what if you don't want to use the docker? I never want to user the image when I am trying things.

2020-11-20 17:55 UTC, arnaudbore approved these changes

2020-11-20 17:55 UTC, merged